[package]
name = "pyrust"
version = "0.1.0"
edition = "2021"

[dependencies]
ymcrust = {git = "https://github.com/Ymclash/ymcrust.git"}
nom = "7.0"
float-derive = "0.1.0"
num-traits = "0.2.14"
num-complex = "0.4.6"




[[test]]
name = "lex_test"
path = "tests/lex_test.rs"

